### ISSUE TITLE
некорректный разбор некоторых полей

### ISSUE THREAD

**Issue by shuratn** [shuratn/py_pdf_stm#2]
по файлу mcu_cache.json:

- "MK02FN128VFM10" : "CCyhclic Reck (eCdRunC)dancy": "LQFP144  TFBGA100". И также дла некоторых контроллеров далее
- не отображаются доступные корпуса, все для тогоже MK02FN128VFM10 указан только LQFP, хотя есть еще и TFBGA

**Comment by REDxEYE** [comment]
"CCyhclic Reck (eCdRunC)dancy" для этого есть config.json
По поводу второго - посмотрю

**Comment by shuratn** [comment]
Это баги в самом даташите.
